//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppGai
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doc
    {
        public int idDoc { get; set; }
        public string nameDoc { get; set; }
    
        public virtual Driver Driver { get; set; }
    }
}
